apiVersion: v1
kind: Pod
metadata:
  name: static-web
  annotations:
    k8s.v1.cni.cncf.io/networks: "bridge-nad"
spec: 
  containers: 
    - name: kube-rbac-proxy
      image: quay.io/coreos/kube-rbac-proxy:v0.5.0
      args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - --upstream=http://127.0.0.1:1984/
        - --tls-private-key-file=/etc/metrics/tls.key
        - --tls-cert-file=/etc/metrics/tls.crt
      ports:
        - containerPort: 8443
          name: https

# this is just to make a pod that won't work, for debug :)